services:
  calibre:
    image: linuxserver/calibre:latest
    restart: always
    environment:
      - KOMGA_CONFIGDIR=/config
    ports:
      - 52335:8080
      - 52334:8081
    volumes:
      - /var/services/homes/calibre/Books:/books
      - /var/services/homes/calibre:/config

  calibre-web:
    image: linuxserver/calibre-web:latest
    restart: always
    environment:
      - KOMGA_CONFIGDIR=/config
    ports:
      - 49155:8083
    volumes:
      - /var/services/homes/calibre:/config

  komga:
    image: gotson/komga:latest
    restart: always
    environment:
      - KOMGA_CONFIGDIR=/config
    ports:
      - 52333:8080
    volumes:
      - /var/services/homes/komga/data:/data
      - /var/services/homes/komga/config:/config

  nginx:
    image: nginx:latest
    restart: always
    network_mode: "host"
    volumes:
      - /var/services/homes/nginx/nginx.conf:/etc/nginx/nginx.conf

  mealie:
    image: hkotel/mealie:latest
    restart: always
    ports:
      - 52336:80
    volumes:
      - /var/services/homes/mealie:/app/data/
